export type EmailField = { label: string; value: string };

export type EmailTemplateInput = {
  title: string;
  intro: string;
  fields: EmailField[];
  message?: string;
};

const escapeHtml = (s: string) =>
  s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");

export function renderEmailHtml({
  title,
  intro,
  fields,
  message,
}: EmailTemplateInput): string {
  const rows = fields
    .filter((f) => f.value && f.value.trim().length > 0)
    .map(
      (f) => `
        <tr>
          <td style="padding:14px 0;border-bottom:1px solid #e5e7eb;vertical-align:top;width:38%;">
            <span style="display:block;font-family:Inter,Arial,sans-serif;font-size:12px;font-weight:600;letter-spacing:.04em;text-transform:uppercase;color:#6b7280;">${escapeHtml(f.label)}</span>
          </td>
          <td style="padding:14px 0;border-bottom:1px solid #e5e7eb;vertical-align:top;">
            <span style="display:block;font-family:Inter,Arial,sans-serif;font-size:15px;line-height:1.55;color:#0f172a;">${escapeHtml(f.value)}</span>
          </td>
        </tr>`,
    )
    .join("");

  const messageBlock = message
    ? `
        <tr>
          <td colspan="2" style="padding:22px 0 0 0;">
            <span style="display:block;font-family:Inter,Arial,sans-serif;font-size:12px;font-weight:600;letter-spacing:.04em;text-transform:uppercase;color:#6b7280;margin-bottom:8px;">Message</span>
            <div style="font-family:Inter,Arial,sans-serif;font-size:15px;line-height:1.65;color:#0f172a;background:#f8fafc;border:1px solid #e5e7eb;border-radius:10px;padding:16px 18px;white-space:pre-wrap;">${escapeHtml(message)}</div>
          </td>
        </tr>`
    : "";

  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <title>${escapeHtml(title)}</title>
  </head>
  <body style="margin:0;padding:0;background:#f1f5f9;">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#f1f5f9;padding:32px 16px;">
      <tr>
        <td align="center">
          <table role="presentation" width="600" cellpadding="0" cellspacing="0" border="0" style="max-width:600px;width:100%;background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 8px 24px rgba(15,23,42,.08);">
            <!-- Header -->
            <tr>
              <td style="background:#ffffff;padding:28px 32px 22px 32px;border-bottom:1px solid #e5e7eb;">
                <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">
                  <tr>
                    <td style="vertical-align:middle;">
                      <img src="cid:fls-logo" alt="FLS Systems Integrity" width="120" style="display:block;height:auto;max-width:120px;" />
                    </td>
                    <td align="right" style="vertical-align:middle;">
                      <span style="display:inline-block;font-family:Inter,Arial,sans-serif;font-size:11px;font-weight:600;letter-spacing:.08em;text-transform:uppercase;color:#004B80;background:#eff6ff;border:1px solid #bfdbfe;padding:6px 12px;border-radius:999px;">New Submission</span>
                    </td>
                  </tr>
                </table>
              </td>
            </tr>
            <!-- Brand accent bar -->
            <tr>
              <td style="background:linear-gradient(90deg,#004B80 0%,#00355a 100%);height:4px;line-height:4px;font-size:0;">&nbsp;</td>
            </tr>

            <!-- Title strip -->
            <tr>
              <td style="padding:28px 32px 8px 32px;">
                <h1 style="margin:0 0 8px 0;font-family:Inter,Arial,sans-serif;font-size:22px;line-height:1.3;font-weight:700;color:#0f172a;">${escapeHtml(title)}</h1>
                <p style="margin:0;font-family:Inter,Arial,sans-serif;font-size:14px;line-height:1.6;color:#475569;">${escapeHtml(intro)}</p>
              </td>
            </tr>

            <!-- Fields table -->
            <tr>
              <td style="padding:12px 32px 28px 32px;">
                <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">
                  ${rows}
                  ${messageBlock}
                </table>
              </td>
            </tr>

            <!-- Footer -->
            <tr>
              <td style="background:#0b1c2c;padding:22px 32px;">
                <p style="margin:0 0 4px 0;font-family:Inter,Arial,sans-serif;font-size:12px;line-height:1.5;color:#cbd5e1;">FLS Systems Integrity Ltd. — Independent fire &amp; life safety verification.</p>
                <p style="margin:0;font-family:Inter,Arial,sans-serif;font-size:11px;line-height:1.5;color:#94a3b8;">This message was generated by the FLS website contact form.</p>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>`;
}

export function renderEmailText({
  title,
  intro,
  fields,
  message,
}: EmailTemplateInput): string {
  const lines = [
    title,
    "=".repeat(title.length),
    "",
    intro,
    "",
    ...fields
      .filter((f) => f.value && f.value.trim().length > 0)
      .map((f) => `${f.label}: ${f.value}`),
  ];
  if (message) {
    lines.push("", "Message:", message);
  }
  lines.push("", "—", "FLS Systems Integrity");
  return lines.join("\n");
}
